const banks={1:[['🐱','cat'],['🐶','dog'],['🍎','apple'],['🚗','car'],['🏠','house'],['☀️','sun'],['🐟','fish'],['⚽','ball']],2:[['🦁','lion'],['🐘','elephant'],['🍌','banana'],['🚲','bicycle'],['📚','books'],['🌳','tree'],['👟','shoes'],['🚌','bus']],3:[['🏥','hospital'],['📚','library'],['✈️','airport'],['🍽️','restaurant'],['☔','umbrella'],['🧳','suitcase'],['🛒','shopping cart'],['🚉','train station']],4:[['🛂','passport control'],['🎫','boarding pass'],['🧑‍🍳','chef'],['🗺️','map'],['🛎️','reception'],['💊','medicine'],['📅','appointment'],['🌡️','temperature']]};
const sentences={1:['I like cats','This is a dog','I have a ball','The sun is yellow'],2:['She rides a bicycle','There are two books','I eat a banana','The elephant is big'],3:['Where is the train station','I would like some water','Can you help me please','I am going to the library'],4:['Could you tell me the way','I would like to book a room','What do you think about it','I have been learning English']};
const shuffle=a=>[...a].sort(()=>Math.random()-.5),board=document.querySelector('#board'),feedback=document.querySelector('#feedback');let mode='match',points=0,round=0,locked=false,chosen=null,open=[],matched=0,pairs=[],built=[],target='',question=0;
function speak(t){if(!('speechSynthesis' in window)){feedback.textContent='الصوت غير متاح في هذا المتصفح';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.8;speechSynthesis.speak(u)}
function status(){document.querySelector('#score').textContent=`⭐ ${points} points · ${matched} / ${mode==='sentence'?1:mode==='listen'?5:pairs.length} completed`}
function finish(){feedback.textContent='🎉 Great job! أحسنت! جرّب جولة جديدة.';locked=true;status()}
function render(){round++;locked=false;chosen=null;open=[];matched=0;built=[];question=0;feedback.textContent='';const level=document.querySelector('#level').value;pairs=shuffle(banks[level]).slice(0,5);document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode)});status();
if(mode==='match'){board.innerHTML='<h2>Connect the picture to its word</h2><p dir="rtl">اختر صورة ثم الكلمة المطابقة. استخدم النقر أو لوحة المفاتيح.</p><div class="match-columns"><div>'+pairs.map((p,i)=>`<button class="picture" data-picture="${i}" aria-label="Picture ${i+1}">${p[0]}</button>`).join('')+'</div><div>'+shuffle(pairs.map((p,i)=>({p,i}))).map(({p,i})=>`<button data-word="${i}">${p[1]}</button>`).join('')+'</div></div>'}
if(mode==='memory'){const cards=shuffle(pairs.flatMap((p,i)=>[{i,t:p[0]},{i,t:p[1]}]));board.innerHTML='<h2>Find the pairs</h2><p dir="rtl">اقلب بطاقتين لتجد الصورة والكلمة. تذكّر مكانهما!</p><div class="memory-grid">'+cards.map((c,k)=>`<button data-memory="${k}" data-pair="${c.i}" data-text="${c.t}" aria-label="Hidden card ${k+1}">?</button>`).join('')+'</div>'}
if(mode==='listen')listen();
if(mode==='sentence'){target=shuffle(sentences[level])[0];board.innerHTML='<h2>Build a sentence</h2><p dir="rtl">استمع للجملة ثم رتّب الكلمات. اضغط كلمة في الإجابة لإرجاعها.</p><button data-speak="sentence">🔊 Hear the sentence</button><div class="answer tiles" id="answer"></div><div class="tiles" id="pool">'+shuffle(target.split(' ')).map((w,i)=>`<button data-tile="${i}">${w}</button>`).join('')+'</div><button data-check="1">✅ Check / تحقق</button>'}}
function listen(){const p=pairs[question];board.innerHTML='<h2>Listen and choose</h2><p dir="rtl">اضغط الاستماع، ثم اختر الصورة المطابقة للكلمة.</p><button data-speak="word">🔊 Listen</button><div class="tiles">'+shuffle(pairs.map((p,i)=>({p,i}))).map(({p,i})=>`<button class="picture" data-listen="${i}" aria-label="Picture ${i+1}">${p[0]}</button>`).join('')+'</div>'}
board.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||locked)return;const token=round;
if(b.dataset.picture!==undefined){board.querySelectorAll('[data-picture]').forEach(x=>x.classList.remove('selected'));chosen=+b.dataset.picture;b.classList.add('selected');feedback.textContent='اختر الكلمة المطابقة الآن.'}
if(b.dataset.word!==undefined){if(chosen===null){feedback.textContent='اختر صورة أولاً.';return}if(chosen===+b.dataset.word){const p=board.querySelector(`[data-picture="${chosen}"]`);[b,p].forEach(x=>{x.disabled=true;x.classList.add('matched');x.classList.remove('selected')});speak(pairs[chosen][1]);chosen=null;points+=10;matched++;feedback.textContent='✅ Correct! صحيح';status();if(matched===pairs.length)finish()}else feedback.textContent='حاول مرة أخرى! Look carefully.'}
if(b.dataset.memory!==undefined){if(open.includes(b))return;b.textContent=b.dataset.text;b.setAttribute('aria-label',b.dataset.text);open.push(b);if(open.length===2){locked=true;const [a,c]=open;if(a.dataset.pair===c.dataset.pair){[a,c].forEach(x=>{x.disabled=true;x.classList.add('matched')});points+=10;matched++;speak(pairs[+a.dataset.pair][1]);open=[];locked=false;status();if(matched===pairs.length)finish()}else setTimeout(()=>{if(token!==round)return;open.forEach(x=>{x.textContent='?';x.setAttribute('aria-label','Hidden card')});open=[];locked=false},850)}}
if(b.dataset.speak)speak(b.dataset.speak==='sentence'?target:pairs[question][1]);
if(b.dataset.listen!==undefined){if(+b.dataset.listen===question){points+=10;matched++;question++;feedback.textContent='✅ Correct!';status();if(question===pairs.length)finish();else listen()}else feedback.textContent='Try again! اضغط الاستماع مرة أخرى.'}
if(b.dataset.tile!==undefined){document.querySelector(b.parentElement.id==='pool'?'#answer':'#pool').appendChild(b)}
if(b.dataset.check){const answer=[...document.querySelector('#answer').children].map(x=>x.textContent).join(' ');if(answer===target){points+=20;matched=1;speak(target);finish()}else feedback.textContent='جرّب ترتيبًا آخر، واستمع للجملة مرة أخرى.'}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render()});document.querySelector('#new').onclick=render;document.querySelector('#level').onchange=render;const requested=new URLSearchParams(location.search).get('level');if(banks[requested])document.querySelector('#level').value=requested;render();
