(()=>{
const icons={cat:'🐱',dog:'🐶',fish:'🐟',hat:'🎩',bag:'🎒',sun:'☀️',mother:'👩',father:'👨',sister:'👧',brother:'👦',happy:'😃',tired:'🥱',book:'📖',pencil:'✏️',chair:'🪑',hand:'✋',eyes:'👀',ears:'👂',apple:'🍎',water:'💧',bread:'🍞',milk:'🥛',rice:'🍚',ball:'⚽',car:'🚗',bike:'🚲',house:'🏠',bed:'🛏️',kitchen:'🍳',bedroom:'🛏️',bathroom:'🛁',garden:'🌳',door:'🚪',window:'🪟',school:'🏫',breakfast:'🥣',lunch:'🥪',dinner:'🍽️',swim:'🏊',football:'⚽',read:'📚',dance:'💃',sing:'🎤',run:'🏃',shop:'🛍️',money:'💰',doctor:'🧑‍⚕️',headache:'🤕',rain:'🌧️',sunny:'☀️',rainy:'🌧️',cold:'🥶',hot:'🥵',park:'🌳',library:'📚',hospital:'🏥',left:'⬅️',right:'➡️',straight:'⬆️'};
const picture=w=>icons[w.toLowerCase()]||(['🔤','🌈','🚀','🎯','💬','⭐'][unit.level-1]);
const words=document.querySelector('#words');words.className='word-deck';words.innerHTML=unit.words.map(([w,a])=>`<button class="word-flip" aria-pressed="false" aria-label="${w}: اقلب واستمع"><span class="word-inner"><span class="word-face"><span class="word-picture" aria-hidden="true">${picture(w)}</span>${w}<small>اضغط لتقلب وتسمع 🔊</small></span><span class="word-face back">${w}<span dir="rtl">${a}</span><small>🔊 Listen • Say • Remember</small></span></span></button>`).join('');words.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true'));speakText(unit.words[i][0])});
const panel=document.createElement('section');panel.className='lesson practice-panel';panel.innerHTML='<h2>🎮 Your challenge zone · ساحة التحديات</h2><p dir="rtl">24 تحديًا في كل درس: 6 وصل، و6 استماع، و6 ترتيب حروف، و6 بناء جمل. اختر لعبة واجمع النجوم!</p><div class="practice-tabs"><button data-practice="match">🖼️ وصل المعنى</button><button data-practice="listen">🎧 اسمع واختر</button><button data-practice="spell">🧩 رتّب الحروف</button><button data-practice="sentence">💬 ابنِ جملة</button></div><p class="practice-score" aria-live="polite"></p><div class="practice-stage"></div><p class="practice-feedback" role="status"></p><button class="practice-restart">🔄 أعد اللعبة</button>';words.closest('section').after(panel);
const sentences=[...unit.dialogue,...unit.text.split(/[.!?]/).map(s=>s.trim()).filter(Boolean)].slice(0,6);let mode='match',index=0,stars=0,built=[],completed=new Set(),locked=false;const stage=panel.querySelector('.practice-stage'),feedback=panel.querySelector('.practice-feedback');const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function score(){panel.querySelector('.practice-score').textContent=`⭐ ${stars} نجمة · ${completed.size} / 24 تحديًا`}
function win(){if(locked)return;locked=true;const key=mode+index;if(!completed.has(key)){completed.add(key);stars++}feedback.textContent='🎉 أحسنت! استمع وكرّر الكلمة ثم تابع.';feedback.classList.remove('practice-win');void feedback.offsetWidth;feedback.classList.add('practice-win');speakText(mode==='sentence'?sentences[index]:unit.words[index][0]);score();const next=document.createElement('button');next.textContent=index<5?'التحدي التالي →':'🏆 انتهت الجولة — اختر لعبة أخرى';next.onclick=()=>{if(index<5){index++;render()}else{index=0;mode=mode==='match'?'listen':mode==='listen'?'spell':mode==='spell'?'sentence':'match';render()}};stage.append(next)}
function render(){locked=false;built=[];feedback.textContent='';panel.querySelectorAll('[data-practice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.practice===mode)));const [word,meaning]=unit.words[index],w=mode==='sentence'?sentences[index]:word,a=mode==='sentence'?'استمع ثم رتّب الكلمات':meaning;stage.innerHTML=`<p>${index+1} / 6</p>`;score();if(mode==='spell'||mode==='sentence'){stage.innerHTML+=`<p class="practice-prompt">رتّب لتكوين الإجابة: <span dir="rtl">${a}</span> <button class="hear">🔊</button></p><div class="sentence-slot" aria-live="polite"></div><div class="practice-options"></div><button class="undo">↶ تراجع</button>`;const options=stage.querySelector('.practice-options');shuffle((mode==='sentence'?w.split(' '):[...w]).map((c,i)=>({c,i}))).forEach(({c})=>{const b=document.createElement('button');b.textContent=c===' '?'␣':c;b.onclick=()=>{if(locked)return;built.push({c,b});b.disabled=true;update()};options.append(b)});function update(){stage.querySelector('.sentence-slot').textContent=built.map(x=>x.c).join(mode==='sentence'?' ':'');if(built.length===(mode==='sentence'?w.split(' ').length:w.length)){if(built.map(x=>x.c).join(mode==='sentence'?' ':'')===w)win();else feedback.textContent='جرّب ترتيبًا آخر. اضغط تراجع أو أعد اللعبة.'}}stage.querySelector('.undo').onclick=()=>{if(locked)return;const last=built.pop();if(last)last.b.disabled=false;feedback.textContent='';update()};stage.querySelector('.hear').onclick=()=>speakText(w)}else{stage.innerHTML+=mode==='match'?`<p class="practice-prompt"><span class="big-picture" aria-hidden="true">${picture(w)}</span><span dir="rtl">${a}</span></p>`:'<p class="practice-prompt">🎧 اسمع الكلمة واخترها</p><button class="hear">🔊 استمع مرة أخرى</button>';const options=document.createElement('div');options.className='practice-options';shuffle(unit.words).forEach(([option])=>{const b=document.createElement('button');b.textContent=option;b.onclick=()=>{if(locked)return;if(option===w){b.classList.add('correct');win()}else{feedback.textContent='💪 حاول مرة أخرى، أنت تستطيع!';b.disabled=true}};options.append(b)});stage.append(options);if(mode==='listen')stage.querySelector('.hear').onclick=()=>speakText(w)}}
panel.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>{mode=b.dataset.practice;index=0;render()});panel.querySelector('.practice-restart').onclick=()=>{index=0;render()};render();
})();

